### PR TITLE
Do not override `name` method.

### PR DESCRIPTION
**Pull request by greyblake**
When I have an enumerated model with column `name` and option `:name_column => :something_other` I can't access value of `name` since it returns value of `something_other`.
This patch fixes the issue. I also write a spec. Sorry for removed trailing spaces.

### CODE REVIEW

**Comment by albertosaurus** [comment]
This breaks the semantics of power_enum, and at least one third-party project that uses it.  Beyond that, how does it answer the question of "What is the name of the enumerated instance I have?"

**Comment by greyblake** [comment]
I expect that  `name_column` is meant to be used for this. People usually know which columns they have in DB and likely call them instead of using `name` alias.

**Comment by albertosaurus** [comment]
In actuality, the expectation is that every enum has a 'name' property that uniquely identifies it.  If you really need to solve this problem, you need a mechanism to override the 'name' property.  Possibly something like `acts_as_enumerated :name_property => 'status_name', :name_column => 'status_name'`.

**Comment by greyblake** [comment]
I guess what you're suggesting is more confusing. OK, leave it.

**Comment by cryo28** [comment]
@albertosaurus I have long since proposed #to_s instead of name and #to_sym instead of name_sym. In my opininion this would better suit semantic of enum with ANY column containing enum item identifier (name, something other etc). 

However, I didn't stumble upon any problems with aliasing as all my enums have always had "name" column. Nevertheless, I think that my proposition still makes sense. The only problem I see is the one you already mentioned: plenty of places in our code depend on #name and #name_sym methods. So we'll have to find and replace them all.

**Comment by albertosaurus** [comment]
Our code isn't the problem, it's the existing third-party users.

Folks, if you think you can achieve genuine wins by changing the semantics, fork the project.  If it proves that you're right, I'll happily deprecate this one and switch to your fork.

**Comment by albertosaurus** [comment]
This functionality has been implemented in version 0.9.0.  I'm closing this.  What you need to do is:

``` ruby
acts_as_enumerated :name_column => :foo, :alias_name => false
```

**Comment by greyblake** [comment]
Wow, great! Thanks @albertosaurus!

**Pull request closed without merging**
