### PR TITLE
Conform to model generators for extra behavior

### PR DESCRIPTION
**Pull request by zbelzer**
While re-running a bootstrapping script that uses generators, I noticed that I could safely re-run the defacto model generators from active record, but not the enum generators.

I found that there was a bit of custom behavior in place to mimic what `NamedBase` was already providing the `Migration` generator in active record, so I switched to `NamedBase` as a superclass.

```
Finished in 14.63 seconds
182 examples, 0 failures

Randomized with seed 16369

Coverage report generated for RSpec to /home/zbelzer/repos/power_enum/coverage. 469 / 471 LOC (99.58%) covered.
```

### CODE REVIEW

**Comment by albertosaurus** [comment]
For some reason this breaks in Travis. I'll need to debug.

**Comment by zbelzer** [comment]
OK. Let me know if I need to change anything.

**Comment by albertosaurus** [comment]
I doubt you did anything wrong. Testing generators has proven to be a nightmare.

**Comment by zbelzer** [comment]
I can see that. I was going to expand some specs and got really fucking confused. I settled with not breaking any.

**Comment by albertosaurus** [comment]
I've released your changes to rubygems. Please note that if you're planning
to use PowerEnum with Rails 4 your need versions 2.X. The 1.X releases are
only for Rails 3.X.

**Comment by zbelzer** [comment]
Thanks @albertosaurus

**Pull request merged**
